# vim: ai et ts=2 st=2 sw=2 :
---
- name: Remove resolvconfd package
  package:
    name: resolvconf
    state: absent

- name: Distribute resolv.conf template
  template:
    src: resolv.conf
    dest: /etc/resolv.conf
    mode: 0644
